---
driver:
    name: vagrant
    synced_folders:
        - ["../../atc", "/usr/local/src/atc/atc"]
    network:
        - ["private_network", {type: "dhcp"}]

provisioner:
    name: chef_solo

platforms:
    - name: ubuntu-12.04
    - name: ubuntu-14.04
    - name: centos-6.6
      attributes:
        python:
            install_method: "source"
            distribute_install_py_version: "2.7"
#    - name: centos-7.0

suites:
    - name: default
      run_list:
        - recipe[python]
        - recipe[atc::default]
